# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MentF.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import csv
import sqlsuname
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def edmark(self):
        f1 = open('sname.txt', 'r')
        r1 = f1.read()
        f1.close()
        l=[]
        r2=sqlsuname.uname(r1)
        with open("target.csv", "a+", newline='') as f:
            reader = csv.reader(f)
            exit = 0
            for i in reader:
                if i[0] == r2:
                    exit = 1
                    i[1] = self.lineEdit.text()
                    i[2] = self.lineEdit_2.text()
                    i[3] = self.lineEdit_3.text()
                    i[4] = self.lineEdit_4.text()
                l.append(i)
            if exit == 0:
                l.append([r2, self.lineEdit.text(), self.lineEdit_2.text(), self.lineEdit_3.text(), self.lineEdit_4.text()])
            writer = csv.writer(f)
            writer.writerows(l)
            Form.close()
        f.close()


    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(480, 720)
        Form.setMinimumSize(QtCore.QSize(480, 720))
        Form.setMaximumSize(QtCore.QSize(480, 720))
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 30, 451, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        Form.setStyleSheet("background: rgb(134,186,212);")

        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(30, 170, 161, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(30, 250, 241, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(30, 330, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(30, 400, 181, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(300, 178, 81, 41))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit.setStyleSheet("background-color: rgb(185,215,230);\n"
                                    "font:20px;")
        self.lineEdit.setText("N/A")
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(300, 257, 81, 41))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_2.setStyleSheet("background-color: rgb(185,215,230);\n"
                                      "font:20px;")
        self.lineEdit_2.setText("N/A")
        self.lineEdit_3 = QtWidgets.QLineEdit(Form)
        self.lineEdit_3.setGeometry(QtCore.QRect(300, 335, 81, 41))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_3.setStyleSheet("background-color: rgb(185,215,230);\n"
                                      "font:20px;")
        self.lineEdit_3.setText("N/A")
        self.lineEdit_4 = QtWidgets.QLineEdit(Form)
        self.lineEdit_4.setGeometry(QtCore.QRect(300, 415, 81, 41))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_4.setStyleSheet("background-color: rgb(185,215,230);\n"
                                      "font:20px;")
        self.lineEdit_4.setText("N/A")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(300, 500, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.setStyleSheet("QPushButton{\n"
"background:rgba(254, 234, 230);\n"
"background: rgb(185,215,230);\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton:hover{\n"
"color:rgba(255,255,255);\n"
"background: rgba(0, 0, 0,200);\n"
"border-radius: 10px;\n"
"}")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(310, 130, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        f1=open('sname.txt','r')
        r1=f1.read()
        f1.close()
        r2=sqlsuname.uname(r1)
        f=open('target.csv','r')
        cr=csv.reader(f)
        for row in cr:
            if(row[0] == r2):
                self.lineEdit.setText(row[1])
                self.lineEdit_2.setText(row[2])
                self.lineEdit_3.setText(row[3])
                self.lineEdit_4.setText(row[4])

        f.close()
        self.pushButton.clicked.connect(self.edmark)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "View/Edit Target"))
        self.label_2.setText(_translate("Form", "Data Science"))
        self.label_3.setText(_translate("Form", "Machine Learning"))
        self.label_4.setText(_translate("Form", "Big Data"))
        self.label_5.setText(_translate("Form", "Mathematics"))
        self.pushButton.setText(_translate("Form", "Save"))
        self.label_6.setText(_translate("Form", "Target"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
