# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hello.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import csv
from threading import Thread
from PyQt5 import QtCore, QtGui, QtWidgets
import subprocess
class Ui_Form(object):
    def cls(self):
        Form.close()
        subprocess.call(['python','main.py'])
    def showDate(self, date):
        dt=date.toString()
        with open('remaind.csv','r+',newline='') as f:
            reader = csv.reader(f)
            for i in reader:
                if dt == i[0] and i[1]!='':
                    with open("remaindt.txt",'w') as g:
                        g.write(i[1])
            subprocess.call(['python','remainderT.py'])

    def cstop(self):
        subprocess.call(['python','stop.py'])
    def tctarget(self):
        a=Thread(target=self.ctarget())
        a.start()
    def ctarget(self):
        subprocess.call(['python','target.py'])
    def ttoggle(self):
        b=Thread(target=self.toggle())
        b.start()

    def toggle(self):
        global process
        process = subprocess.Popen(['python', 'toggle.py'])
        # self.pushButton_5.raise_()
        self.pushButton.hide()
    def ctoggle(self):
        process.terminate()
        self.pushButton.show()
    # def showDate(self, date):
        # print(date.toString())
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setEnabled(True)
        Form.resize(480, 720)
        Form.setMinimumSize(QtCore.QSize(480, 720))
        Form.setMaximumSize(QtCore.QSize(480, 720))
        font = QtGui.QFont()
        font.setPointSize(8)
        Form.setFont(font)
        Form.setStyleSheet("background: rgb(134,186,212)")
        self.label = QtWidgets.QLabel(Form)
        self.label.setEnabled(True)
        self.label.setGeometry(QtCore.QRect(50, 60, 391, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel{\n"
"background:transparent;\n"
"color: rgb(0, 0, 0);\n"
"}\n"
"")
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(20, 10, 51, 41))
        self.pushButton.setStyleSheet("\n"
"QPushButton{\n"
"background:rgba(255,255,255);\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 10px;\n"
"image: url(:/newPrefix/toggle.png);\n"
"}\n"
"\n"
"")
        self.pushButton.setText("")
        self.pushButton.setIconSize(QtCore.QSize(64, 64))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.ttoggle)
        self.calendarWidget = QtWidgets.QCalendarWidget(Form)
        self.calendarWidget.setEnabled(True)
        self.calendarWidget.setGeometry(QtCore.QRect(30, 150, 411, 241))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.calendarWidget.setFont(font)
        self.calendarWidget.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.calendarWidget.setMinimumDate(QtCore.QDate(2020, 1, 1))
        self.calendarWidget.setMaximumDate(QtCore.QDate(2025, 12, 31))
        self.calendarWidget.setGridVisible(True)
        self.calendarWidget.setHorizontalHeaderFormat(QtWidgets.QCalendarWidget.SingleLetterDayNames)
        self.calendarWidget.setVerticalHeaderFormat(QtWidgets.QCalendarWidget.NoVerticalHeader)
        self.calendarWidget.setNavigationBarVisible(True)
        self.calendarWidget.setDateEditEnabled(True)
        self.calendarWidget.setObjectName("calendarWidget")
        self.calendarWidget.clicked.connect(self.showDate)
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setEnabled(True)
        self.pushButton_2.setGeometry(QtCore.QRect(140, 450, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"background:rgba(254, 234, 230);\n"
"background: rgb(185,215,230);\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton:hover{\n"
"color:rgba(255,255,255);\n"
"background: rgba(0, 0, 0,200);\n"
"border-radius: 10px;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.tctarget)
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setEnabled(True)
        self.pushButton_3.setGeometry(QtCore.QRect(140, 540, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"background:rgba(254, 234, 230);\n"
"background: rgb(185,215,230);\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton:hover{\n"
"color:rgba(255,255,255);\n"
"background: rgba(0, 0, 0,200);\n"
"border-radius: 10px;\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.clicked.connect(self.cstop)
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setEnabled(True)
        self.pushButton_4.setGeometry(QtCore.QRect(200, 660, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("QPushButton{\n"
"background:rgba(254, 234, 230);\n"
"background: rgb(185,215,230);\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton:hover{\n"
"color:rgba(255,255,255);\n"
"background: rgba(0, 0, 0,200);\n"
"border-radius: 10px;\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_4.clicked.connect(self.cls)
        self.pushButton_5 = QtWidgets.QPushButton(Form)
        self.pushButton_5.setGeometry(QtCore.QRect(20, 10, 51, 41))
        self.pushButton_5.setStyleSheet("\n"
"QPushButton{\n"
"background:rgba(255,255,255);\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 10px;\n"
"image: url(:/newPrefix/switch.png);\n"
"}")
        self.pushButton_5.setText("")
        self.pushButton_5.setIconSize(QtCore.QSize(64, 64))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_5.raise_()
        self.pushButton_5.clicked.connect(self.ctoggle)
        self.label.raise_()
        self.pushButton.raise_()
        self.calendarWidget.raise_()
        self.pushButton_2.raise_()
        self.pushButton_3.raise_()
        self.pushButton_4.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        with open('mentee.txt','r') as f:
            a=f.read()
        self.label.setText(_translate("Form", f"Hello {a}"))
        self.pushButton_2.setText(_translate("Form", "Submit Target"))
        self.pushButton_3.setText(_translate("Form", "Study Time"))
        self.pushButton_4.setText(_translate("Form", "Log Out"))
import gui_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
