# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MentD.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import urllib.request
import webbrowser
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def google(self):
        url = 'https://github.com/curiouscoders07/study_materials'
        webbrowser.open_new_tab(url)
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(480, 720)
        Form.setMinimumSize(QtCore.QSize(480, 720))
        Form.setMaximumSize(QtCore.QSize(480, 720))
        Form.setStyleSheet("background-color: rgb(134,186,212);")

        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(20, 20, 211, 121))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(30, 160, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(30, 380, 301, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(18)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(340, 170, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.google)
        self.pushButton.setStyleSheet("QPushButton{\n"
"background:rgba(185,215,230);\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton:hover{\n"
"color:rgba(255,255,255);\n"
"background: rgba(0, 0, 0,200);\n"
"border-radius: 10px;\n"
"}")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(340, 390, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.google)
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"background:rgba(185,215,230);\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton:hover{\n"
"color:rgba(255,255,255);\n"
"background: rgba(0, 0, 0,200);\n"
"border-radius: 10px;\n"
"}")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Resources"))
        self.label_2.setText(_translate("Form", "Reference"))
        self.label_3.setText(_translate("Form", "Practice Questions"))
        self.pushButton.setText(_translate("Form", "View File"))
        self.pushButton_2.setText(_translate("Form", "View File"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
