# -*- coding: utf-8 -*-
from PyQt5.QtWidgets import QPushButton

# Form implementation generated from reading ui file 'MentB.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from functools import partial
import sqlstulist
import subprocess
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(480, 720)
        Form.setMinimumSize(QtCore.QSize(480, 720))
        Form.setMaximumSize(QtCore.QSize(480, 720))
        Form.setStyleSheet("background-color: rgb(134,186,212);")
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        Form.setFont(font)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(20, 50, 251, 81))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 160, 441, 451))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")

        # create a list of button labels
        button_labels = sqlstulist.stlist()

        # create and add push buttons to the vertical layout
        for label in button_labels:
            button = QPushButton(label, Form)
            button.setStyleSheet('''background:transparent;
            font-size:30px''')
            self.verticalLayout.addWidget(button)
            self.verticalLayout.addWidget(button)
            button.clicked.connect(partial(self.on_button_clicked, label))

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def on_button_clicked(self, label):
        f=open('sname.txt', 'w')
        f.write(label)
        f.close()
        # print(label, "clicked!")
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        subprocess.call(['python', 'sthome.py'])

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Student List"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
